Create entities crud operations
Woselko/Actively pull request #8
Opened 2024-01-07 20:38 UTC by EmilBulka

2024-01-10 19:38 UTC, Woselko commented on Actively/Actively/ActivelyApp/Controllers/GameController.cs
> +            IEnumerable<GameDto> games = new List<GameDto>();
Why do we initialize List<GameDto> in line 28 if we override it in line 32. I think we should declare a "games" variable here

2024-01-10 20:35 UTC, Woselko requested changes

2024-01-10 20:35 UTC, Woselko commented on Actively/Actively/ActivelyApp/Controllers/GameController.cs
> +                { Type = ResponseType.Error, Status = Common.Error, Message = e.Message, IsSuccess = false });
we cannot return Message = e.Message because we have multilingual application. If you want to return a message, please add proper resources

2024-01-10 20:35 UTC, Woselko commented on Actively/Actively/ActivelyApp/Controllers/GameController.cs
> +                { Type = ResponseType.Error, Status = Common.Error, Message = e.Message, IsSuccess = false });
we cannot return Message = e.Message because we have multilingual application. If you want to return a message, please add proper resources

2024-01-10 20:35 UTC, Woselko commented on Actively/Actively/ActivelyApp/Controllers/GameController.cs
> +                { Type = ResponseType.Error, Status = Common.Error, Message = e.Message, IsSuccess = false });
we cannot return Message = e.Message because we have multilingual application. If you want to return a message, please add proper resources

2024-01-10 20:35 UTC, Woselko commented on Actively/Actively/ActivelyApp/Controllers/GameController.cs
> +                { Type = ResponseType.Error, Status = Common.Error, Message = e.Message });
we cannot return Message = e.Message because we have multilingual application. If you want to return a message, please add proper resources

2024-01-10 20:35 UTC, Woselko commented on Actively/Actively/ActivelyApp/Controllers/GameController.cs
> +                { Type = ResponseType.Error, Status = Common.Error, Message = e.Message, IsSuccess = false });
we cannot return Message = e.Message because we have multilingual application. If you want to return a message, please add proper resources

2024-01-10 20:35 UTC, Woselko commented on Actively/Actively/ActivelyApp/Services/EntityService/GameService.cs
> +            }
Ogolnie ladnie to wyglada, ale widze jedna rzecz, napisze po polsku:
zrobie to na przykladzie tego Taska Delete(int id).

uzywamy tego Taska GmaeService.Delete() np w GameController kod poniżej:

 [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _gameService.Delete(id);
            }
            catch(**NotFoundEntityException**)
            {
                return StatusCode(StatusCodes.Status404NotFound, new Response
                { Type = ResponseType.Error, Status = Common.Error, Message = Common.GameNotExistsError, IsSuccess = false });
            }


w kontrolerze chcesz złapac wyjątek **NotFoundEntityException**, który zostanie zjedzony niepotrzebnie w GameServisie. Trzeba to pozmieniac bo teraz nigdy nie dojdziesz do catch'a w kontrolerze.
W efekcie dostalem
![image](https://github.com/Woselko/Actively/assets/76818798/6358b51e-3b7f-442a-84ab-35c16fe74487)
z pustą bazą danych :P

2024-01-10 20:35 UTC, Woselko commented on Actively/Actively/ActivelyApp/Services/EntityService/GameService.cs
> +            }
i generalnie we wszystkich tych serwisach zle handlujesz wyjatki, zjadamy je i w efekcie return succes jest

2024-01-10 20:35 UTC, Woselko commented on Actively/Actively/ActivelyApp/Controllers/PlayerController.cs
> +                if (players == null)
players nigdy nie bedzie null, bo GetAll() zwroci albo uzupelnioną liste albo pustą. ale nie null

2024-01-10 20:35 UTC, Woselko commented on Actively/Actively/ActivelyApp/Controllers/PlayerController.cs
> +            catch (Exception e)
i ten exception zostanie zjedzony w metodzie GetAll()

2024-01-10 20:35 UTC, Woselko commented on Actively/Actively/ActivelyApp/Services/EntityService/GameService.cs
> +            }
tak samo w testach
                    _mockGameService.Setup(service => service.Delete(id)).ThrowsAsync(new NotFoundEntityException(Common.GameNotExistsError));
                    
realnie mock czy tez serwis nigdy nie rzucilby tym wyjatkiem, bo zostal zjedzony, chyab ze bylby rethrow

2024-01-30 00:01 UTC, EmilBulka commented on Actively/Actively/ActivelyApp/Controllers/GameController.cs
> +                { Type = ResponseType.Error, Status = Common.Error, Message = e.Message, IsSuccess = false });
done

2024-01-30 00:01 UTC, EmilBulka commented on Actively/Actively/ActivelyApp/Controllers/GameController.cs
> +                { Type = ResponseType.Error, Status = Common.Error, Message = e.Message, IsSuccess = false });
done

2024-01-30 00:02 UTC, EmilBulka commented on Actively/Actively/ActivelyApp/Controllers/GameController.cs
> +                { Type = ResponseType.Error, Status = Common.Error, Message = e.Message });
done

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/PlayerServiceTests.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/PlayerServiceTests.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/PlayerServiceTests.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/PlayerServiceTests.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/PlayerServiceTests.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/PlayerServiceTests.cs
> +            }
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/PlayerServiceTests.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/PlayerServiceTests.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/PlayerServiceTests.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/PlayerServiceTests.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/GameServiceTest.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/GameServiceTest.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/GameServiceTest.cs
> +            };
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/GameServiceTest.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/GameServiceTest.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/GameServiceTest.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/GameServiceTest.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/GameServiceTest.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/GameServiceTest.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ServicesTests/PlayerServiceTests.cs
> +
remove empty lines

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/RepositoriesTests/PlayerRepositoryTests.cs
> +    public class PlayerRepositoryTests : IDisposable
remove empty lines in the file

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/RepositoriesTests/GameRepositoryTests.cs
> +
remove empty lines in the file

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ControllersTests/PlayerControllerTests.cs
> +
remove empty lines in file

2024-01-31 22:12 UTC, Woselko commented on Actively/Actively/ActivelyTests/ActivelyApp.Tests/ControllersTests/GameControllerTests.cs
> +
remove empty lines in the file

2024-01-31 22:42 UTC, Woselko approved these changes, later dismissed

2024-01-31 22:59 UTC, Woselko approved these changes

2024-01-31 23:00 UTC, merged